### ISSUE TITLE
Uncaught Error: Could not find module `tracked-maps-and-sets/-private/util` imported from `(require)`

### ISSUE THREAD

**Issue by oleg-andreyev** [NullVoxPopuli/ember-deep-tracked#211]
util file is available only on < 3.0.0
https://github.com/tracked-tools/tracked-maps-and-sets/tree/v2.2.1/src/-private

**Comment by NullVoxPopuli** [comment]
oh that explains it. PRs welcome! I don't know how soon until I'll be able to look at this <3

**Comment by NullVoxPopuli** [comment]
This package probably needs to use the storage primitives, like what tracked-built-ins and tracked-maps-and-sets had to go through:

Related PRs:
 - https://github.com/tracked-tools/tracked-built-ins/pull/161
 - https://github.com/tracked-tools/tracked-maps-and-sets/pull/103

**Comment by courajs** [comment]
In the meantime, if you are using yarn, you can add the following to package.json:
```
  "resolutions": {
    "ember-deep-tracked/tracked-maps-and-sets": "2.2.1"
  },
```

Or, you can just pin `ember-deep-tracked` to `1.2.5`, but you will lose deep array tracking.

**Comment by NullVoxPopuli** [comment]
I've started a WIP PR in #213 -- it's not done yet, but if anyone needs updates ASAP, that'd be the place to start
